[workspace]

members = [
    "transformation",
    "approximation",
    "coding",
    "checksums",
    "base"
]

# Check profiles for release, bin, and bench
# https://doc.rust-lang.org/cargo/reference/profiles.html
