[workspace]

members = [
    "rscompress-transformation",
    "rscompress-approximation",
    "rscompress-coding",
    "rscompress-checksums",
    "rscompress"
]

# Check profiles for release, bin, and bench
# https://doc.rust-lang.org/cargo/reference/profiles.html
