# GitHub Actions setup based on https://shift.click/blog/github-actions-rust/
name: CI
env:
    RUST_BACKTRACE: 1
on:
    pull_request:
    push:
        branches:
            - "master"
jobs:
    test:
        name: Test Rust ${{ matrix.rust }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                # supported os versions: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
                include:
                    - { rust: stable, os: macos-10.15 }
                    - { rust: stable, os: windows-2019 }
                    - { rust: stable, os: ubuntu-20.04 }
                    - { rust: beta, os: ubuntu-20.04 }
                    - { rust: nightly, os: ubuntu-20.04 }
        steps:
            - uses: actions/checkout@v2
            - name: Install rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.rust }}
            - run: cargo test --workspace --all-features
    clippy:
        name: Check with clippy
        runs-on: ubuntu-20.04
        env:
            RUSTFLAGS: -Dwarnings
        steps:
            - uses: actions/checkout@v2
            - name: Install rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                components: clippy
            - run: cargo clippy --workspace --all-features
    rust-fmt:
        name: Check formatting
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                components: rustfmt
            - run: cargo fmt --all --verbose -- --check
    code-coverage:
        name: Generate code coverage
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - name: Install and run tarpaulin
              uses: actions-rs/tarpaulin@v0.1
              with:
                args: --all-features  # check if this can be extended
    benchmark:
        name: Benchmark code
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Install rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - run: cargo bench --all-features --all
